### ISSUE TITLE
Android - handleOpenURL not called when app is already opened.

### ISSUE THREAD

**Issue by kimras** [EddyVerbruggen/Custom-URL-scheme#68] opened 2015-03-10 19:09 UTC
First of all thanks for all the work on this plug in..! 
I have run into an odd issue.. If the app is closed and I start it with the URLScheme it starts and it calls the handleOpenURL() function.. but if I leave the app open and recall the URLScheme, it will start the app, but the handleOpenURL() function is not called.. 
On iOS it seams to work fine even if the app. already is runing.

Any clue ?

Android 5.0.2, 
Phonegap version 3.6.3 (Using build)

**Comment by feoche** [comment] 2015-03-23 16:56
Hello, 

I have also the same problem. I am forced to kill the launched app in order to handle URL callback.
I am currently with the 3.2.2 version of this plugin, and it should have been fixed in #13, but it's not.

Any ideas?

Regards.

**Comment by EddyVerbruggen** [comment] 2015-04-07 19:32
@feoche can you share your project with me perhaps?

**Comment by iver56** [comment] 2015-04-12 15:07
I have this issue too
Android 4.1.1
Cordova 3.7.1
Ionic framework: 1.0.0-RC2

**Comment by EddyVerbruggen** [comment] 2015-04-16 13:33
Avoid Cordova-iOS 3.7. If that doesn't help feel free to post a link to your app so I can inspect it.

**Closed by EddyVerbruggen** 2015-04-16 13:33 UTC

**Comment by stianjensen** [comment] 2015-04-16 14:55
The issue is with android, not iOS

**Comment by EddyVerbruggen** [comment] 2015-04-16 15:07
I need a project to debug this. Feel free to send something to eddyverbruggen at gmail

**Comment by dustinblanchard** [comment] 2015-06-17 22:01
Has anybody had any luck with this?

**Comment by dustinblanchard** [comment] 2015-06-17 22:16
Removing && intent.getScheme() != null && intent.getScheme().contains("://") from line 41 & 42 of LaunchMyApp.java fixes it. @EddyVerbruggen any reason to keep this in there? If not I can pull request.

**Comment by EddyVerbruggen** [comment] 2015-06-17 22:18
I fixed that about an hour ago ;)
Sorry for the trouble..

**Comment by dustinblanchard** [comment] 2015-06-17 22:21
Awesome! Thank you for all of your hard work on this.

**Comment by 17holeinone** [comment] 2016-04-09 08:44
I join everyone in saying thanks for your time creating this plugin ... I'm having an issue with handleOpenURL not being called ...

Long time ago when I started the project I did setup a custom URL scheme not using your plugin (I don't even remember how), now I've installed your plugin, the app does open up when I click on a web page with my custom URL, but I can't get the handleOpenURL function to be called. I've tried placing it at the bottom of the app.js file, I've added it also to the index file, but nothing ...

For testing I've tried this (at the bottom of app,js):

console.log("About to define handleOpenURL");
 function handleOpenURL(url) {
// This function is triggered by the LaunchMyApp Plugin
     console.log("RECEIVED URL: " + url);
}

When the app starts I do see the "About to define handleOpenURL" comment, so I know it gets here, but that's it, it never goes in ...

How can I tell if your plugin is even properly installed? Maybe the app is still just opening up because of my previous attempt :-)

Please advise ... thanks.

**Comment by ils-mrunalij** [comment] 2016-10-15 11:49
Hello,

Please help me regarding this..As handleOpenURL function does not call In my iOS device so I am unable to get the url..It is just opening the app.

**Comment by rajneshkis13** [comment] 2017-11-29 12:02
@EddyVerbruggen Can you share your solution which got work? I am facing same issue. I also tried removing mentioned lines from Launchmyapp.java file but no luck!!
